// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
import 'package:firebase_core/firebase_core.dart';

/// Firebase options for your project
const firebaseOptions = FirebaseOptions(
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
  measurementId: "YOUR_MEASUREMENT_ID",
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgEKNVsiyyCTE-FTXR9Bji_YGvHOxiG2c',
    appId: '1:953093278087:web:78f720ebe9fbd321d92b22',
    messagingSenderId: '953093278087',
    projectId: 'finquest2-8af5e',
    authDomain: 'finquest2-8af5e.firebaseapp.com',
    storageBucket: 'finquest2-8af5e.appspot.com',
    measurementId: 'G-HM06B6DG6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yczsPgRLQBzgDE-3LEX_Sg3YEH22l4Y',
    appId: '1:953093278087:android:29b6250b9a8fdfadd92b22',
    messagingSenderId: '953093278087',
    projectId: 'finquest2-8af5e',
    storageBucket: 'finquest2-8af5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1YdwaNtX5NREyu6_CYWTuXiVtT4kosAQ',
    appId: '1:953093278087:ios:969e7a5995c94534d92b22',
    messagingSenderId: '953093278087',
    projectId: 'finquest2-8af5e',
    storageBucket: 'finquest2-8af5e.appspot.com',
    iosBundleId: 'com.example.finquest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1YdwaNtX5NREyu6_CYWTuXiVtT4kosAQ',
    appId: '1:953093278087:ios:969e7a5995c94534d92b22',
    messagingSenderId: '953093278087',
    projectId: 'finquest2-8af5e',
    storageBucket: 'finquest2-8af5e.appspot.com',
    iosBundleId: 'com.example.finquest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgEKNVsiyyCTE-FTXR9Bji_YGvHOxiG2c',
    appId: '1:953093278087:web:0d880e1f73bad33bd92b22',
    messagingSenderId: '953093278087',
    projectId: 'finquest2-8af5e',
    authDomain: 'finquest2-8af5e.firebaseapp.com',
    storageBucket: 'finquest2-8af5e.appspot.com',
    measurementId: 'G-QDQMK7XB58',
  );

}